### ISSUE TITLE
Allow to use ServiceLoader in Eclipse context

### ISSUE THREAD

**Issue by soerendomroes** [kieler/KLighD#64]
Currently either extension points or ServiceLoader are used. However, it should also be possible to use in an Eclipse context.
This would simplify registration of several components and would enable us to slowly migrate to ServiceLoaders.

**Comment by soerendomroes** [comment]
Is this fixed in the new KlighD release?

**Comment by NiklasRentzCAU** [comment]
As discussed before the release, we now allow to avoid this problem by using the `startupHook` extension point, where all extensions can be registered programatically once without having to use extension points or service loaders for any of the other extensions anymore. As not all extensions could be converted to service loader definitions because of additional properties of the extensions, this was the way to go without breaking any existing API.
