### ISSUE TITLE
Maven artifacts for release 2.0

### ISSUE THREAD

**Issue by eNBeWe** [kieler/KLighD#78]
You published nice artifacts for KlighD version 1.1.0. 
Is there a similar deployment for version 2.0 planned?

**Comment by sailingKieler** [comment]
It actually was but we haven't been bored enough to do so ;-)

**Comment by a-sr** [comment]
The [Lingua Franca](https://github.com/icyphy/lingua-franca) project uses Gradle to build its plugins, which makes it quite hard to use p2 sources. Having Klighd artifacts on MavenCentral would be very helpful.
Can we revive this and include publishing artifacts in Maven in release process?

**Comment by sailingKieler** [comment]
We should, at least, revive building the maven artifacts for releases, maybe I find some time during summer.
I'm a bit hesitant to push to maven central, as somebody should then be the "Kümmerer" and take care on account data (if necessary), etc.

**Comment by a-sr** [comment]
That would be really nice. Being able to build a language server including Klighd using Gradle would make things a lot easier in Lingua Franca. Currently, there is a (preferred) Gradle build for the LF compiler CLI and an additional Maven build for Eclipse and Klighd.

I am sure we can find a solution for the administrative stuff of Maven Central but if these Maven artifacts can also be used in Gradle without Maven Central that would be fine too.

For now, I will set up a maven shade build for the language server with Klighd but if a Grade build will be possible in the near future that would be great because maintain all these build configuration is not fun.
